# Welcome to Jupyter Lab tutorial
## Level 2
### Level 3

this is tutorial to go over Python.

# Python Tutorial Notebook


#### Basic Syntax

```python

result_list = [output_exp for var in input_list if (condition on var is true)]
```

In [4]:
nums = range(100)
squares = []

for num in nums:
    squares.append(num**2) # num * num

In [3]:
nums = range(100)
squares = [num**2 for num in nums]

In [5]:
nums = range(100)
odd_squares = []

for num in nums:
    if num % 2 == 1: # Odd value
        odd_squares.append(num**2)

In [7]:
# list comprehensions are (often) more concise
nums = range(100)
odd_squares = [num ** 2 for num in nums if num % 2 == 1]

#### Dict comprehensions

In [8]:
nums = range(100)
# Empty dictionary (hashtable.)
odd_dict = {}

for num in nums:
    if num % 2 == 1: # Odd
        odd_dict[num] = num **2
        # e.g., key: 3 => value: 3 *3

In [10]:
nums = range(100)
odd_dict = {num : num ** 2 for num in nums if num % 2 == 1}


- Jupyter notebooks provide built-in commands called **magics** to address common problems in the data analysis workflow



#### Timing

- likely the most useful magic functions are `time` and `timeit`

- `time` times the amount of time used for a single run of the line of code or cell
- `timeit` runs multiple trials of the line of code or cell to provide a more accurate measurement of the execution time

In [11]:
%time odd_squares = [num ** 2 for num in range(100000) if num % 2 == 1]

CPU times: user 55.6 ms, sys: 8.81 ms, total: 64.4 ms
Wall time: 66.9 ms


In [12]:
%timeit odd_squares = [num ** 2 for num in range(10000) if num % 2 == 1]

6.75 ms ± 984 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
# we can also time entire cells
%time

nums = range(100000)
odd_squares = []

for num in nums:
    if num % 2 == 1:
        odd_squares.append(num**2)

CPU times: user 7 µs, sys: 1 µs, total: 8 µs
Wall time: 17.2 µs


In [14]:
%%timeit

nums = range(100000)
odd_squares = []

for num in nums:
    if num % 2 == 1:
        odd_squares.append(num**2)

76 ms ± 23.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### Other useful Magics

- `%who_ls`: lists all active variables in the namespace
- `%reset`: resets the namespace and all named variables
- `%debug`: activate the python debugger
- `%lsmagic`: list all the available magic commands

### Out of Scope?

- A quirk of Python variables is that they are scoped to the innermost function, and control blocks like `if` don't count

In [22]:
# Will this code throw an exception? What is the output?
if True:
    x = "I've been initialized!"
print(x)

I've been initialized!


In [23]:
# Will this code throw an exception? What is the output?
if False:
    x = "I've been initialized!"
print(x)

I've been initialized!


### Imports

- we need to import the NumPy module below in order to use it
- we often use the `as` syntax to alias the module name to an abbreviation

In [15]:
# subsequent references to the numpy module can use 'np'
import numpy as np

### Rolling 5 Dice



```python
y = np.zeros(5)       
roll_idx = np.array(range(5))
y[roll_idx] = np.floor(np.random.uniform(0,6, roll_idx.shape))
```

---


- `np.zeros(5)` creates an array of zeros of shape (5,)
  - **Note:** this is a 1D array with 5 elements, which is different than an 2D array with only one column, shape (5,1)
- `np.array(range(5))` creates an array \[0,1,2,3,4\] of shape (5,)
- `np.random.uniform(0,6, roll_idx.shape)` samples from the uniform distribution in the range \[0, 6) in the given shape
- `np.floor` rounds down to the nearest integer
  - **Note:** we're using zero-indexed dice, so our possible rolls are \[0,1,2,3,4,5\]
  
*Tip: If you are unsure of a function's arguments or return signature, you can run `help(function_name)` to print the docstring*

In [16]:
help(np.random.uniform)

Help on built-in function uniform:

uniform(...) method of numpy.random.mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)
    
    Draw samples from a uniform distribution.
    
    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.
    
    .. note::
        New code should use the ``uniform`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : float or array_like of floats, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float or array_like of floats
        Upper boundary of the output interval.  All values generated will be
        less than or equal to high.  The default value is 1.0.
    size : int or tuple o

#### What is the value and shape of y?

In [17]:
y = np.zeros(5)       
roll_idx = np.array(range(5))
y[roll_idx] = np.floor(np.random.uniform(0,6, roll_idx.shape))
print(y)
print(y.shape)

[4. 5. 3. 0. 1.]
(5,)


In [29]:
y = np.zeros((5,1))       
roll_idx = np.array(range(5))
# note the need for a second index, since y is now a 2D array!
y[roll_idx, 0] = np.floor(np.random.uniform(0,6, roll_idx.shape))
print(y)
print(y.shape)

[[2.]
 [4.]
 [5.]
 [4.]
 [1.]]
(5, 1)


In [30]:
y = np.zeros((5,5))       
roll_idx = np.array(range(5))
# : is shorthand for selecting all indices along an axis. More on indexing later
# What happens if we run y[:, roll_idx] instead?
y[roll_idx, :] = np.floor(np.random.uniform(0,6, roll_idx.shape))
print(y)
print(y.shape)

[[0. 5. 0. 0. 5.]
 [0. 5. 0. 0. 5.]
 [0. 5. 0. 0. 5.]
 [0. 5. 0. 0. 5.]
 [0. 5. 0. 0. 5.]]
(5, 5)


### Re-rolling

#### Random number generation
```python
np.random.seed(0)
```

---

- `np.random.seed(0)` sets the seed of the Numpy's random number generator to 0, ensuring that subsequent calls to `np.random` functions are reproducible
  - note that any `int`, not just 0, will work as a reproducible seed

In [31]:
# Here we're using the random seed to make sure our first roll is reproducible
np.random.seed(0)
y = np.zeros(5)       
roll_idx = np.array(range(5))
y[roll_idx] = np.floor(np.random.uniform(0,6, roll_idx.shape))
print(y)

[3. 4. 3. 3. 2.]


- 3 is the most common, so we want to re-roll indices 1 and 4

#### How do we get the indices to re-roll?

In [18]:
# check which entries of y aren't 3 
y != 3

array([ True,  True, False,  True,  True])

In [33]:
# return the indices that are "True" -- interpreted as non-zero by Numpy
# note the return shape! np.nonzero returns a tuple of arrays, one for each axis
np.nonzero(y != 3)

(array([1, 4]),)

In [34]:
# assign the new roll_idx
roll_idx = np.nonzero(y != 3)[0]
print(roll_idx)

[1 4]


#### The general re-roll case


In [36]:
# count the number of dice we've rolled for each number
counts = [sum(y == i) for i in range(6)]
print(counts)

[0, 0, 1, 3, 1, 0]


In [37]:
# Find the idx of the most common roll
max_idx = np.argmax(counts)
print(max_idx)

3


In [38]:
# update the indices to re-roll accordingly
roll_idx = np.nonzero(y != max_idx)[0]    
print(roll_idx)

[1 4]


### Putting it all together

In [42]:
def yamslam():
    """Plays one round of yamslam, re-rolling 5 dice up to 3 times.
  
  Also prints exuberantly if we do get a yamslam.
  
  Returns:
    int: 1 if we got a yamslam, 0 if not
      """
    y = np.zeros(5)       
    roll_idx = np.array(range(5))
    for reroll in range(3): # 3 rerolls
        y[roll_idx] = np.floor(np.random.uniform(0,6,roll_idx.shape))
        counts = [sum(y == i) for i in range(6)]
        max_idx = np.argmax(counts)

    if np.max(counts) == 5:
        print('YAMSLAM!')
        return 1
    
    roll_idx = np.nonzero(y != max_idx)[0]  
    
  # we've run all 3 re-rolls but still didn't get a yamslam
    return 0      

#### Running multiple trials

In [43]:
%%time

yamslam_trials = []
for i in range(100):
    yamslam_trials.append(yamslam())
    
print("Probability of yamslam: {}".format(np.mean(yamslam_trials)))

Probability of yamslam: 0.0
CPU times: user 162 ms, sys: 8.1 ms, total: 170 ms
Wall time: 300 ms


#### Improving the code

```python
counts = [sum(y == i) for i in range(6)]
max_idx = np.argmax(counts)
```

---

- `np.bincounts` produces the same result for `count` as our list comprehension

- More importantly, what is the above code effectively calculating?

In [19]:
# We're calculating the mode!
from scipy.stats import mode

np.random.seed(0)
y = np.zeros(5)       
roll_idx = np.array(range(5))
y[roll_idx] = np.floor(np.random.uniform(0,6, roll_idx.shape))
roll_idx = np.nonzero(y != mode(y)[0])[0]  

*Tip: before implementing a mathematical operation, check the documentation to see if it's already part of the library -- chances are, it is.*

## Working with Arrays

### Vectorization

- before writing a loop, consider if the operation can be *vectorized*
- vectorization is the application of an operation over an entire array, instead of element by element
- Results in more concise code, and many vectorized implementations of functions are optimized

In [20]:
%%timeit

# Don't do this!!
vec = np.array(range(10000))
sum_v = 0
for i in range(10000):
    sum_v += vec[i]

14.7 ms ± 5.81 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
%%timeit

# Vectorize instead
vec = np.array(range(10000))
sum_v = np.sum(vec)

4.73 ms ± 1.42 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Watch the axes

- What is the behavior of  `np.sum()` if our array has more than one dimension?
- Use the `axis` argument: specifies which axis to sum along
- Many other vectorized functions take the axis argument, so keep in mind which dimension you want the operation applied to

In [ ]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)
print(A.shape)

In [ ]:
# By default, axis=None and np.sum will sum all elements of the array
print(np.sum(A))

In [ ]:
# axis=0 sums along rows, producing column totals
print(np.sum(A, axis=0))

In [ ]:
# axis=0 sums along columns, producing row totals
print(np.sum(A, axis=1))

- vectorization doesn't always work -- post to Piazza or come to office hours if you have questions!

### Indexing

#### Slicing

- the standard rules of slicing and indexing from Python apply to Numpy arrays
- `i:j:k` syntax corresponds to starting at index `i`, ending at index `j` with step size `k`
  - omitting `k` implies a step size of 1
- `i:` selects all indices beginning at index `i`
- `:j` selects all indices up to but not including index `j`
- `:` by itself selects all indices along an axis

In [ ]:
# start with list of 0 to 9
vec = np.array(range(10))
print(vec)

In [ ]:
# selects indices 2,3,4 (not including 5)
print(vec[2:5])

In [ ]:
# selects indices 2,4,6
print(vec[2:7:2])

In [ ]:
# selects indices starting with 5 to the end
print(vec[5:])

In [ ]:
# selects indices up to, but not including, index 5
print(vec[:5])

In [ ]:
# select everything, since vec is a 1D array
print(vec[:])

In [ ]:
# same idea with 2D arrays, but with two axes
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)

In [ ]:
# select the element in the 0-index row and 1-index column
print(A[0,1])

In [ ]:
# select the 0-index column
print(A[:, 0])

In [ ]:
# select the first two rows
print(A[:2, :])

In [ ]:
# select the last two columns of the last two rows
print(A[1:, 1:])

#### Logical Indexing

- we can select according to boolean conditions across axes as well

In [ ]:
%%timeit

np.random.seed(0)
num_animals = 100000
animal_weights = np.random.uniform(0, 50, num_animals)

# Don't do this!!
is_dog = np.zeros(num_animals)
is_cat = np.zeros(num_animals)

for i in range(num_animals):
  if animal_weights[i] > 30:
    is_dog[i] = 1
  else:
    is_cat[i] = 1

In [ ]:
%%timeit

np.random.seed(0)
num_animals = 100000
animal_weights = np.random.uniform(0, 50, num_animals)

# Use logical indexing instead, see the speed difference
is_dog = animal_weights > 30
is_cat = animal_weights <= 30

In [ ]:
np.random.seed(0)
num_animals = 100000
animal_weights = np.random.uniform(0, 50, num_animals)

# Use logical indexing for conditional selections
dog_weights = animal_weights[animal_weights > 30]
cat_weights = animal_weights[animal_weights <= 30]